# Generated by Django 5.1.4 on 2024-12-16 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_rename_address1_shippingaddress_shipping_address1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='shipping_fullname',
            new_name='shipping_full_name',
        ),
    ]
