# Generated by Django 5.1.4 on 2024-12-16 15:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_shippingaddress_shipping_address2_order_items'),
        ('store', '0004_profile_old_cart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='items',
            new_name='Orderitem',
        ),
    ]
